app/controllers/client.py
from flask import (
    Blueprint,
    render_template, 
    g,
    request,
    session,
    redirect,
    url_for,
    flash
)
import flask_login

from app import app
from app.forms import user as user_forms
import json
from json import dumps

# database
from app.models.monitoring import Monitoring
from app.models.client import Client
from app.models.user import User

from app.libraries.session import usersession as USession

# Create a document blueprint
clientbp = Blueprint('clientbp', __name__, url_prefix='/client')


@app.before_request
def before_request():
    g.user = None
    if 'user' in session:
        # find user based on userid, update information user
        user = session['user']
        g.user = user

        user = USession.User()
        # TODO: place your user / account data
        user.npk = g.user["npk"]
        user_data = User()
        person, message = user_data.profile(user.npk)

        if len(person) == 0:
            return render_template('handler/error.html', title='Error Page', message="Data user belum terdaftar di Approval Online")

        user.name = person['name']
        user.company = person['company']
        user.division = person['divisionid']
        user.department = person['departmentid']

        # save to session
        session["usersession"] = user.__dict__
        flask_login.login_user(user)



@clientbp.route('/api/1.0/clients')
@flask_login.login_required
def api_1_0_clients():
    # try to get list of client
    client = Client()
    result, message = client.list_client()
    return {
        "success": "0" if result == [] else "1",
        "message": message,
        "data": result
    }


@clientbp.route('/api/1.0/profile/<npk>')
@flask_login.login_required
def api_1_0_profile(npk):
    user = User()
    person, message = user.profile(npk)
    return {
        "success": "0" if person == None else "1",
        "message": message,
        "data": person
    }


@clientbp.route('/browse')
@flask_login.login_required
def browse():
    if not g.user:
        return render_template('handler/error.html', title='Error Page', message="Harap lakukan login terlebih dahulu!")
    
    if g.user["npk"] != session["usersession"]["npk"]:
        return redirect('https://10.10.108.44/login')
    
    return render_template('client/browse.html', title='Clients')

app/controllers/main.py
from flask import (
    render_template, 
    g,
    request,
    session,
    redirect,
    url_for
)
import flask_login
from app import app
from app.api import security 

from app.models.user import User

from app.models.dashboards import Dashboards
from app.libraries.session import usersession as USession

@app.before_request
def before_request():
    g.user = None
    if 'user' in session:
        # find user based on userid, update information user
        user = session['user']
        g.user = user

        user = USession.User()
        # TODO: place your user / account data
        user.npk = g.user["npk"]
        user_data = User()
        person, message = user_data.profile(user.npk)

        if len(person) == 0:
            return render_template('handler/error.html', title='Error Page', message="Data user belum terdaftar di Approval Online")

        user.name = person['name']
        user.company = person['company']
        user.division = person['divisionid']
        user.department = person['departmentid']

        # save to session
        session["usersession"] = user.__dict__
        flask_login.login_user(user)


@app.route('/', methods = ['GET'])
@app.route("/index")
def index():
    return render_template('index.html', title="Approval Online")


@app.route('/home', methods = ['GET'])
@flask_login.login_required
def home():
    if not g.user:
        return render_template('handler/error.html', title='Error Page', message="Harap lakukan login terlebih dahulu!")
    
    if g.user["npk"] != session["usersession"]["npk"]:
        return redirect('https://10.10.108.44/login')
    
    # usersession = session["usersession"]
    dashboard = Dashboards()

    # Total Dashboards
    result, message = dashboard.total_dashboards(g.user["npk"])
    
    return render_template('home.html', title="Approval Online", request=result)

app/templates/layouts/fullscreen.html
<!DOCTYPE html>
{% import "macros.html" as m %}
<html lang="en">
<head>
	<meta name='viewport' content='initial-scale=1,maximum-scale=1,user-scalable=no' />
	<meta charset="UTF-8">
	<link rel="shortcut icon" href="{{ url_for('static', filename='img/favicon.ico') }}">

	<!-- bootstrap -->
    <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap-4.3.1-min.css') }}"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
	
	<!-- Semantic Main CSS -->
	<link rel="stylesheet" href="{{ url_for('static', filename='css/semantic-main.css') }}" />
	<!-- Semantic Reset CSS -->
	<link rel="stylesheet"
	href="{{ url_for('static', filename='css/semantic-reset.css') }}" />
	<!-- Semantic Menu CSS -->
	<link rel="stylesheet"
	href="{{ url_for('static', filename='css/semantic-menu.css') }}" />
	
	<!-- Custom CSS -->
	<link rel="stylesheet" href="{{ url_for('static', filename='css/design-light.css') }}">

	<!-- Quill Better Table -->
	<link href="{{ url_for('static', filename='css/quill-snow.css') }}" rel="stylesheet">
	<link href="{{ url_for('static', filename='css/quill-better-table.css') }}" rel="stylesheet">

	<!-- Fontawesome -->
    <link rel="stylesheet" href="{{ url_for('static', filename='node_modules/lib/fontawesome/css/all.min.css') }}">
	{% block csscustom %} {% endblock %}
</head>
<body id="container">
	<div id="header">
		{% block head %}
		<!-- Browser tab name -->
		<title>{{ title }}</title>
		<!-- Navbar -->
		{% endblock %}
	</div>
	<!-- Message flashing -->
	{% with messages = get_flashed_messages(with_categories=true) %}
	{% if messages %}
	<div class="messages-block">
		{% for category, message in messages %}
		<div class="ui {{ category }} message flash">{{ message }}</div>
		{% endfor %}
	</div>
	{% endif %}
	{% endwith %}
	<div id="body" class="body">
		<main class="content">
			<div class="container-fluid p-0">
				{% block content %}{% endblock %}
			</div>
		</main>
	</div>
	</div>
</body>
<!-- DevExtreme Jquery library -->
<script src="{{ url_for('static', filename='node_modules/lib/devextreme/js/jquery-2.2.3.min.js') }}"></script>

<!-- datepicker -->
<script src="{{ url_for('static', filename='js/datepicker-min.js') }}"
    integrity="sha512-T/tUfKSV1bihCnd+MxKD0Hm1uBBroVYBOYSk1knyvQ9VyZJpc/ALb4P0r6ubwVPSGB2GvjeoMAJJImBG12TiaQ=="
    crossorigin="anonymous" referrerpolicy="no-referrer"></script>

<!-- font awesome -->
<script src="{{ url_for('static', filename='node_modules/lib/fontawesome/js/all.min.js') }}"></script>

<!-- sweetalert -->
<script src="{{ url_for('static', filename='js/sweetalert2.js') }}"></script>

<!-- jquery loadingoverlay -->
<script src="{{ url_for('static', filename='js/loadingoverlay-min.js') }}">
</script>

<!-- default -->
<script src="{{ url_for('static', filename='js/theme.js') }}"></script>
<script src="{{ url_for('static', filename='js/vie.js') }}"></script>
<script src="{{ url_for('static', filename='js/default.js') }}"></script>
<script src="{{ url_for('static', filename='js/common.js') }}"></script>

<!-- bootstrap -->
<script src="{{ url_for('static', filename='js/bootstrap-4.3.1-min.js') }}"
    integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous">
    </script>


<!-- Main Quill library -->
<script src="{{ url_for('static', filename='js/quill-snow.js') }}"></script>
<script src="{{ url_for('static', filename='js/quill-better-table.js') }}"></script>

{% block scriptcustom %} {% endblock %}

</html>

app/templates/layouts/home.html
<!DOCTYPE html>
{% import "macros.html" as m %}
<html lang="en">

<body id="container">
	<div id="header">
		{% block head %}
		<meta name='viewport' content='initial-scale=1,maximum-scale=1,user-scalable=no' />
		<meta charset="UTF-8">
		<link rel="shortcut icon" href="{{ url_for('static', filename='img/favicon.ico') }}">
		<!-- jQuery -->
		<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
		<!-- Semantic Main CSS -->
		<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/1.11.8/semantic.min.css" />
		<!-- Semantic Reset CSS -->
		<link rel="stylesheet"
			href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.1.6/components/reset.min.css" />
		<!-- Semantic Menu CSS -->
		<link rel="stylesheet"
			href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.1.6/components/menu.min.css" />
		<!-- Main Semantic JS  -->
		<script src="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/1.11.8/semantic.min.js"></script>
		<!-- Custom CSS -->
		<link rel="stylesheet" href="{{ url_for('static', filename='css/light.css') }}">
		<link rel="stylesheet" href="{{ url_for('static', filename='css/custom.css') }}">
		<!-- Browser tab name -->
		<title>{{ title }}</title>
		<!-- Navbar -->
		{% endblock %}
	</div>
	<!-- Message flashing -->
	{% with messages = get_flashed_messages(with_categories=true) %}
	{% if messages %}
	<div class="messages-block">
		{% for category, message in messages %}
		<div class="ui {{ category }} message flash">{{ message }}</div>
		{% endfor %}
	</div>
	{% endif %}
	{% endwith %}
	<div id="body" class="body">
		<main class="content">
			<div class="container-fluid p-0">
				{% block content %}{% endblock %}
			</div>
		</main>
	</div>
	<div id="footer">
		<div class="ui divided horizontal footer link list">
			<div class="item">
				sluvie
			</div>
			<div class="item">
				<a href="https://github.com/sluvie"><i class="github icon"></i></a>
			</div>
		</div>
	</div>
	</div>
</body>

</html>

app/templates/layouts/main.html
<!doctype html>
{% import "macros.html" as m %}
<html>

<head>
    <title>{{title}}</title>
    <meta charset="utf-8">
    <meta name="description" content={{description}}>
    <link rel="shortcut icon" href="/favicon.ico">

    <meta name="viewport"
        content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1, user-scalable=no" />

    <!-- fonts -->
    <link href="{{ url_for('static', filename='css/font-google.css') }}" rel="stylesheet">

    <!-- bootstrap -->
    <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap-4.3.1-min.css') }}"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <!-- datepicker -->
    <link rel="stylesheet"
    href="{{ url_for('static', filename='css/datepicker-min.css') }}"
        integrity="sha512-mSYUmp1HYZDFaVKK//63EcZq4iFWFjxSL+Z3T/aCt4IO9Cejm03q3NKKYN6pFQzY0SBOr8h+eCIAZHPXcpZaNw=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />

    <!-- DevExtreme -->
    <link rel="stylesheet" href="{{ url_for('static', filename='node_modules/lib/devextreme/css/dx.common.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='node_modules/lib/devextreme/css/dx.light.css') }}">

    <!-- font awesome -->
    <link rel="stylesheet" href="{{ url_for('static', filename='node_modules/lib/fontawesome/css/all.min.css') }}">

    <!-- default -->
    <link rel="stylesheet" href="{{ url_for('static', filename='css/light.css') }}">

    <style>
        .pagebreak { page-break-before: always; }
    </style>

    {% block csscustom %} {% endblock %}
</head>


<body data-theme="default" data-layout="fluid" data-sidebar-position="left" data-sidebar-behaviour="sticky">
    <div class="wrapper">
        <!-- <nav id="sidebar" class="sidebar">
            <div class="sidebar-content js-simplebar" data-simplebar="init">
                <div class="simplebar-wrapper" style="margin: 0px;">
                    <div class="simplebar-height-auto-observer-wrapper">
                        <div class="simplebar-height-auto-observer"></div>
                    </div>
                    <div class="simplebar-mask">
                        <div class="simplebar-offset" style="right: 0px; bottom: 0px;">
                            <div class="simplebar-content-wrapper" tabindex="0" role="region"
                                aria-label="scrollable content" style="height: 100%; overflow: hidden scroll;">
                                <div class="simplebar-content" style="padding: 0px;">
                                    
                                    <div class="sidebar-cta">
                                        <div class="sidebar-cta-content">
                                            <strong class="d-inline-block mb-2">Request Approval</strong>
                                            <div class="d-grid">
                                                <a href="{{ url_for('submissionbp.request_approval') }}"
                                                    class="btn btn-primary"><i
                                                        class="fa fa-envelope-open"></i>
                                                    Request</a>
                                            </div>
                                        </div>
                                    </div>

                                    <ul class="sidebar-nav">
                                        <li class="sidebar-item">
                                            <a class="sidebar-link" href="/home">
                                                <i class="fa-solid fa-table-columns"></i>
                                                Dashboards
                                            </a>
                                        </li>

                                        <li class="sidebar-header" style="padding-top: 13px">
                                            Approval Tools
                                        </li>   

                                        
                                        <li class="sidebar-item">
                                            <a class="sidebar-link" href="{{ url_for('documentbp.browse') }}">
                                                <i class="fa fa-file"></i>
                                                Documents
                                            </a>
                                        </li>
                                        

                                        
                                        <li class="sidebar-item">
                                            <a class="sidebar-link" href="{{ url_for('submissionbp.submissions') }}">
                                                <i class="fa fa-cloud"></i>
                                                Submissions (Request)
                                            </a>
                                        </li>
                                        

                                        
                                        <li class="sidebar-item">
                                            <a class="sidebar-link" href="{{ url_for('clientbp.browse') }}">
                                                <i class="fa fa-person"></i>
                                                Clients
                                            </a>
                                        </li>
                                        

                                        <li class="sidebar-header">
                                            Report
                                        </li>

                                        
                                        <li class="sidebar-item">
                                            <a data-bs-target="#monitorings" data-bs-toggle="collapse"
                                                class="sidebar-link">
                                                <i class="fa fa-desktop"></i>
                                                Monitorings
                                            </a>
                                            <ul id="monitorings" class="sidebar-drowdown list-unstyled collapse show"
                                                data-bs-parent="#sidebar">
                                                <li class="sidebar-item"><a class="sidebar-link"
                                                        href="{{ url_for('monitoringbp.document') }}"><i
                                                            class="fa fa-file"></i> Document</a></li>
                                                <li class="sidebar-item"><a class="sidebar-link"
                                                        href="{{ url_for('monitoringbp.trackingworkflow') }}"><i class="fa fa-location-dot"></i> Tracking Workflow</a></li>
                                            </ul>
                                        </li>
                                        

                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="simplebar-placeholder" style="width: auto; height: 1254px;"></div>
                </div>
            </div>
        </nav> -->

        <div class="main">
            {% include 'frame/navigation.html' %}
            <div class="content">
                <div class="container-fluid p-0">
                    {% block content %}{% endblock %}
                </div>
            </div>
        </div>
    </div>
</body>

<!-- DevExtreme Jquery library -->
<script src="{{ url_for('static', filename='node_modules/lib/devextreme/js/jquery-2.2.3.min.js') }}"></script>

<!-- bootstrap -->
<script src="{{ url_for('static', filename='js/bootstrap-4.3.1-min.js') }}"
    integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous">
    </script>

<!-- datepicker -->
<script src="{{ url_for('static', filename='js/datepicker-min.js') }}"
    integrity="sha512-T/tUfKSV1bihCnd+MxKD0Hm1uBBroVYBOYSk1knyvQ9VyZJpc/ALb4P0r6ubwVPSGB2GvjeoMAJJImBG12TiaQ=="
    crossorigin="anonymous" referrerpolicy="no-referrer"></script>

<!-- font awesome -->
<script src="{{ url_for('static', filename='node_modules/lib/fontawesome/js/all.min.js') }}"></script>

<!-- sweetalert -->
<script src="{{ url_for('static', filename='js/sweetalert2.js') }}"></script>

<!-- jquery loadingoverlay -->
<script src="{{ url_for('static', filename='js/loadingoverlay-min.js') }}">
</script>

<!-- DevExtreme libraries (reference only one of them) -->
<script src="{{ url_for('static', filename='node_modules/lib/devextreme/js/jszip.min.js') }}"></script>
<script src="{{ url_for('static', filename='node_modules/lib/devextreme/js/dx.all.js') }}"></script>

<!-- sparkline -->
<script src="{{ url_for('static', filename='js/plugins/sparkline/jquery.sparkline.min.js') }}"></script>

<!-- default -->
<script src="{{ url_for('static', filename='js/theme.js') }}"></script>
<script src="{{ url_for('static', filename='js/vie.js') }}"></script>
<script src="{{ url_for('static', filename='js/default.js') }}"></script>
<script src="{{ url_for('static', filename='js/common.js') }}"></script>

{% block scriptcustom %} {% endblock %}

</html>