app/models/submission.py
from app.models.base import BaseTable

class Submission(BaseTable):

    def __init__(self):
        self.__database__ = 'mpmds'
        self.__tablename__ = ''
        super().__init__()


    def submissions(self, npk, status):
        # status approval (0 - draft, 1 - sent)
        result = []
        try:
            data, message = self.callproc("EXEC MPMDS_SUBMISSION_FILTER ?, ?", (npk, int(status), ))
            for x in data:
                row = {
                    'requestapprovalid': x[0],
                    'requestapprovalnumber': x[1],
                    'masterdocid': x[2],
                    'documentnumber': x[3],
                    'requestid': x[4],
                    'companyid': x[5],
                    'divisionid': x[6],
                    'departmentid': x[7],
                    'name': x[8],
                    'desc': x[9],
                    'createdby': x[10],
                    'createddate': x[11],
                    'statusrequest': x[12]
                }
                result.append(row)
            return (result, message)
        except Exception as e:
            print(str(e))
            return (None, str(e))

app/controllers/submissions.py
from flask import (
    Blueprint,
    render_template, 
    g,
    request,
    session,
    redirect,
    url_for,
    flash,
    send_file,
    abort,
    jsonify
)
import flask_login

from app import app
from app.forms import user as user_forms
import json
import ast
import hashlib
import time
import os
from json import dumps
import datetime as dt
from app.libraries.util import parameterquery

# config
import app.config as conf

# database
from app.models.document import Document
from app.models.monitoring import Monitoring
from app.models.approvalonline_files import ApprovalOnlineFiles
from app.models.user import User
from app.models.security import Security
from app.models.submission import Submission
from app.models.requestapproval import RequestApproval
from app.models.requestapproval_answer import RequestApprovalAnswer
from app.models.requestapproval_authentication import RequestApprovalAuthentication

# libraries
from app.libraries.session import security as SecurityBase
from app.libraries.email import email as Email
from app.libraries.manipulationtext import StringUtil
from app.libraries.session import usersession as USession

# Create a document blueprint
submissionbp = Blueprint('submissionbp', __name__, url_prefix='/submission')


@app.before_request
def before_request():
    g.user = None
    if 'user' in session and 'usersession' in session:
        # find user based on userid, update information user
        user = session['user']
        g.user = user

        user = USession.User()
        # TODO: place your user / account data
        user.npk = g.user["npk"]
        user_data = User()
        person, message = user_data.profile(user.npk)

        if len(person) == 0:
            return render_template('handler/error.html', title='Error Page', message="Data user belum terdaftar di Approval Online")

        user.name = person['name']
        user.company = person['company']
        user.division = person['divisionid']
        user.department = person['departmentid']

        # save to session
        session["usersession"] = user.__dict__
        flask_login.login_user(user)


@submissionbp.route('/api/1.0/submissions/<status>')
@flask_login.login_required
def api_1_0_submissions(status):
    if not g.user:
        return render_template('handler/error.html', title='Error Page', message="Harap lakukan login terlebih dahulu!")
    submission = Submission()
    # result, message = submission.submissions(session["usersession"]["npk"], status)
    result, message = submission.submissions(g.user["npk"], status)
    return {
        "success": "0" if result == None else "1",
        "message": message,
        "data": result
    }


@submissionbp.route('/api/1.0/submissions/getdocumentrequest/<divisionid>', methods=['GET'])
@flask_login.login_required
def api_1_0_getdocumentrequest(divisionid):
    if not g.user:
        return render_template('handler/error.html', title='Error Page', message="Harap lakukan login terlebih dahulu!")
    # get company id 
    # usersession = session["usersession"]
    usersession = g.user
    
    # try to get list of document
    document = Document()
    result, message = document.list_document_for_request(usersession["npk"], usersession["company"], divisionid)
    return {
        "success": "0" if result == None else "1",
        "message": message,
        "data": result
    }


@submissionbp.route('/api/1.0/submissions/fillformanswer/<requestapprovalid>', methods=['GET'])
@flask_login.login_required
def api_1_0_submissions_fillformanswer(requestapprovalid):
    requestapprovalanswer = RequestApprovalAnswer()
    result1, message1 = requestapprovalanswer.get_answer(requestapprovalid)
    result2, message2 = requestapprovalanswer.get_answerbase(requestapprovalid)

    answermultirow = []
    
    for x in result2:
        if x["questiontype"] == 1:
            data = {
                'requestapprovalid': requestapprovalid,
                'designdocumentquestionid': x["designdocumentquestionid"],
                'questioncondition': x["questioncondition"],
                'questiontypecomponent': x["questiontypecomponent"]
            }
            resultanswermultirow, messageanswermultirow = requestapprovalanswer.get_answer_multirow(data)
            answermultirow.append(resultanswermultirow)

    resultsinglegroup = [x for x in result1 if x["sectiontype"] == 0]
    resultmultigroup, messagemultigroup = requestapprovalanswer.get_answer_multigroup(requestapprovalid)

    arr2 = {}
    for d in resultmultigroup:
        arr2.setdefault(d['designdocumentgroupquestionid'], []).append(d)

    arr2 = list(arr2.values())
            
    return {
        "success": "0" if result1 == None or result2 == None else "1",
        "message": message1,
        "data": result1,
        "datamultirow": answermultirow,
        "datasinglegroup": resultsinglegroup,
        "datamultigroup": resultmultigroup,
        "arr2": arr2
    }  


@submissionbp.route('/api/1.0/submissions/authrequest/<requestapprovalid>', methods=['GET'])
@flask_login.login_required
def api_1_0_submissions_authrequest(requestapprovalid):
    requestapprovalauthentication = RequestApprovalAuthentication()
    result, message = requestapprovalauthentication.get_authdata(requestapprovalid)

    return {
        "success": "0" if result == None else "1",
        "message": message,
        "data": result
    }


@submissionbp.route('/api/1.0/submissions/filerequest/<requestapprovalid>', methods=['GET'])
@flask_login.login_required
def api_1_0_submissions_filerequest(requestapprovalid):
    approvalonlinefiles = ApprovalOnlineFiles()
    result, message = approvalonlinefiles.get_files(requestapprovalid)

    return {
        "success": "0" if result == None else "1",
        "message": message,
        "data": result
    } 


@submissionbp.route('/request_approval', methods=['GET', 'POST'])
@flask_login.login_required
def request_approval():
    if not g.user:
        return render_template('handler/error.html', title='Error Page', message="Harap lakukan login terlebih dahulu!")
    
    if g.user["npk"] != session["usersession"]["npk"]:
        return redirect('https://10.10.108.44/login')
    
    if request.method == 'POST':
        # usersession = session["usersession"]
        usersession = g.user
        data = {
            "divisionid": request.form['select-division-id'],
            "documentid": request.form['select-document-type'],
            "[desc]": request.form['textarea-notes'],
            "name": request.form['select-document-text'],
            "activeversiondocument": int(request.form['select-designdocument-version']),
            "statusrequest": 0,
            "picrequester": usersession["npk"],
            "deleteflag": 0,
            "createdby": usersession["npk"],
            "createddate": dt.datetime.now(),
            "modifby": "",
            "modifdate": "",
        }
        requestapproval = RequestApproval()
        result, message = requestapproval.insert_data(data)

        if message == "success":
            return redirect(url_for('submissionbp.submissions_fillformrequest', requestapprovalid=result))

    return render_template('submission/request.html', title='Request')


@submissionbp.route('/request_fillform', methods=['POST'])
@flask_login.login_required
def request_fillform():
    questionid = ast.literal_eval(request.form['arrayquestionid'])

    # usersession = session["usersession"]
    usersession = g.user
    requestapprovalanswer = RequestApprovalAnswer()
    arraydata = []

    arraygroupid = ast.literal_eval(request.form['arraygroupid'])
    arraygroupid = [x["uuid"] for x in arraygroupid]

    multirow = False

    for x in questionid:
        if x["sectiontype"] == 0:
            if x["questiontype"] == 0:
                data = {
                    "designdocumentquestionid": x["questionid"],
                    "requestapprovalid": request.form['requestapprovalid'],
                    "answer": request.form[str(x["questionid"])],
                    "createdby": usersession["npk"],
                    "createddate": dt.datetime.now()
                }
                arraydata.append(data)
            else:
                arraymultirow = request.form.getlist(str(x["questionid"]))
                for y in arraymultirow:
                    data = {
                        "designdocumentquestionid": x["questionid"],
                        "requestapprovalid": request.form['requestapprovalid'],
                        "answer": y,
                        "createdby": usersession["npk"],
                        "createddate": dt.datetime.now()
                    }
                    arraydata.append(data)
        else:
            multirow = True

    if multirow:
        for x in arraygroupid:
            for y in questionid:
                try:
                    inputname = f"{x}-{y['questionid']}"
                    answer = request.form[str(inputname)]
                            
                    data = {
                        "designdocumentquestionid": y["questionid"],
                        "requestapprovalid": request.form['requestapprovalid'],
                        "answer": answer,
                        "createdby": usersession["npk"],
                        "createddate": dt.datetime.now(),
                        "answergroupid": x
                    }
                        
                    arraydata.append(data)
                except Exception as e:
                    pass

    result, message = requestapprovalanswer.insert_answer(arraydata, request.form['requestapprovalid'])

    return redirect(url_for('submissionbp.submissions_authorizationrequest', requestapprovalid=request.form['requestapprovalid']))


@submissionbp.route('/request_authorization', methods=['POST'])
@flask_login.login_required
def request_authorization():
    try:
        dataarray = json.loads(request.form['arraymasterapproveid'])

app/templates/submission/authorizationrequest.html
{% extends 'layouts/main.html' %}

{% block content %}

<h3>{{ title }}</h3>

<div class="row mb-3">
    <div class="col-12">
        <div class="page-title-box d-flex align-items-center justify-content-between">
            <h4 style="color: transparent">Pepe Sedati</h4>
            <div class="page-title-right">
                <ol class="breadcrumb m-0" style="background-color: transparent">
                    <li class="breadcrumb-item"><a href="/home">Home</a></li>
                    <li class="breadcrumb-item"><a href="/submission/submissions">Submission</a></li>
                    <li class="breadcrumb-item"><a href="/submission/submissions/fillformrequest/{{ request.requestapprovalid }}">Fill Form</a></li>
                </ol>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <input type="hidden" name="documentid" id="documentid" value="{{ request.masterdocid }}">
    <div class="col-md-3">
        <strong>Request Approval Id</strong>
    </div>
    <div class="col-md-9">
        <strong class="text-warning">{{ request.requestapprovalid }}</strong>
    </div>
    <div class="col-md-3">
        <strong>Request Approval Number</strong>
    </div>
    <div class="col-md-9">
        {{ request.requestapprovalnumber }}
    </div>
    <div class="col-md-3">
        <strong>Document Name</strong>
    </div>
    <div class="col-md-9">
        {{ request.name }}
    </div>
    <div class="col-md-3">
        <strong>Description</strong>
    </div>
    <div class="col-md-9">
        {{ request.desc }}
    </div>
    <div class="col-md-3">
        <strong>Status</strong>
    </div>
    <div class="col-md-9">
        {% if request.statusrequest == 0 %}
        <span class="badge badge-warning">Draft</span>
        {% elif request.statusrequest == 1 %}
        <span class="badge badge-success">Submitted</span>
        {% else %}
        <span class="badge badge-danger">Cancel</span>
        {% endif %}
    </div>
</div>

<hr />
<div class="card flex-fill">
    <div class="card-header">
        <div class="card-actions float-end">
            <div class="dropdown position-relative"></div>
        </div>
    </div>
    <div class="card-body">
        <form class="row" action="{{ url_for('submissionbp.request_authorization') }}" method="post">
            <input type="hidden" name="requestapprovalid" id="requestapprovalid" value="{{ request.requestapprovalid }}" />
            <input type="hidden" name="arraymasterapproveid">
            <div id="authform"></div>
            <div class="col-md-6 offset-md-6">
                <button type="submit" class="btn btn-primary col-12 btn-next"><i class="fa fa-arrow-circle-right" aria-hidden="true"></i>Next</button>
            </div>
        </form>
    </div>
</div>

{% endblock %}

{% block scriptcustom %}

<script src="{{ url_for('static', filename='js/page/submission/authorizationrequest.js') }}"></script>

{% endblock %}

app/templates/submission/fillformrequest.html
{% extends 'layouts/main.html' %}

{% block content %}

<h3>{{ title }}</h3>

<div class="row mb-3">
    <div class="col-12">
        <div class="page-title-box d-flex align-items-center justify-content-between">
            <h4 style="color: transparent">Pepe Sedati</h4>
            <div class="page-title-right">
                <ol class="breadcrumb m-0" style="background-color: transparent">
                    <li class="breadcrumb-item"><a href="/home">Home</a></li>
                    <li class="breadcrumb-item"><a href="/submission/submissions">Submission</a></li>
                </ol>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <input type="hidden" name="documentid" id="documentid" value="{{ request.masterdocid }}">
    <div class="col-md-3">
        <strong>Request Approval Id</strong>
    </div>
    <div class="col-md-9">
        <strong class="text-warning">{{ request.requestapprovalid }}</strong>
    </div>
    <div class="col-md-3">
        <strong>Request Approval Number</strong>
    </div>
    <div class="col-md-9">
        {{ request.requestapprovalnumber }}
    </div>
    <div class="col-md-3">
        <strong>Document Name</strong>
    </div>
    <div class="col-md-9">
        {{ request.name }}
    </div>
    <div class="col-md-3">
        <strong>Description</strong>
    </div>
    <div class="col-md-9">
        {{ request.desc }}
    </div>
    <div class="col-md-3">
        <strong>Status</strong>
    </div>
    <div class="col-md-9">
        {% if request.statusrequest == 0 %}
        <span class="badge badge-warning">Draft</span>
        {% elif request.statusrequest == 1 %}
        <span class="badge badge-success">Submitted</span>
        {% else %}
        <span class="badge badge-danger">Cancel</span>
        {% endif %}
    </div>
</div>

<hr />
<form class="row" action="{{ url_for('submissionbp.request_fillform') }}" method="post">
    <input type="hidden" name="requestapprovalid" id="requestapprovalid" value="{{ request.requestapprovalid }}" />
    <input type="hidden" name="arrayquestionid">
    <input type="hidden" name="arraygroupid">
    <div id="fillform"></div>
    <div class="col-md-6 offset-md-6 right">
        <button type="submit" class="btn btn-primary col-12 btn-next"><i class="fa fa-arrow-circle-right" aria-hidden="true"></i>Next</button>
    </div>
</form>

{% endblock %}

{% block scriptcustom %}

<script src="{{ url_for('static', filename='js/page/submission/fillformrequest.js') }}"></script>
<script src="{{ url_for('static', filename='js/page/submission/fillformrequest_groupmultirow.js') }}"></script>

{% endblock %}

app/templates/submission/postingrequest.html
{% extends 'layouts/main.html' %}

{% block content %}

<h3>{{ title }}</h3>

<script>
    var activeversion = '{{ request.activeversiondocument }}'
    var documentid = '{{ request.masterdocid }}'
    var years = '{{ request.years }}'
    var nosig = '{{ request.nosig }}'
    var layout = '{{ request.layout }}'
    var usersess = '{{ usersession.npk }}'
</script>

<div class="row mb-3">
    <div class="col-12">
        <div class="page-title-box d-flex align-items-center justify-content-between">
            <h4 style="color: transparent">Pepe Sedati</h4>
            <div class="page-title-right">
                <ol class="breadcrumb m-0" style="background-color: transparent">
                    <li class="breadcrumb-item"><a href="/home">Home</a></li>
                    <li class="breadcrumb-item"><a href="/submission/submissions">Submission</a></li>
                    <li class="breadcrumb-item"><a href="/submission/submissions/fillformrequest/{{ request.requestapprovalid }}">Fill Form</a></li>
                    <li class="breadcrumb-item"><a href="/submission/submissions/authorizationrequest/{{ request.requestapprovalid }}">Auth Fill</a></li>
                    <li class="breadcrumb-item"><a href="/submission/submissions/uploadfilerequest/{{ request.requestapprovalid }}">File Upload</a></li>
                </ol>
            </div>
        </div>
    </div>
</div>

<div class="card flex-fill">
    <div class="card-body">
        <div class="row">
            <input type="hidden" name="requestapprovalid" id="requestapprovalid" value="{{ request.requestapprovalid }}">
            <div class="col-md-3">
                <strong>Request Approval Id</strong>
            </div>
            <div class="col-md-9">
                <strong class="text-warning">{{ request.requestid }}</strong>
            </div>
            <div class="col-md-3">
                <strong>Request Approval Number</strong>
            </div>
            <div class="col-md-9">
                {{ request.requestapprovalnumber }}
            </div>
            <div class="col-md-3">
                <strong>Document Name</strong>
            </div>
            <div class="col-md-9">
                {{ request.name }}
            </div>
            <div class="col-md-3">
                <strong>Description</strong>
            </div>
            <div class="col-md-9">
                {{ request.desc }}
            </div>
            <div class="col-md-3">
                <strong>PIC Requester</strong>
            </div>
            <div class="col-md-9">
                {{ request.picname }}
            </div>
            <div class="col-md-3">
                <strong>PIC NPK</strong>
            </div>
            <div class="col-md-9">
                {{ request.picrequester }}
            </div>
            <div class="col-md-3">
                <strong>PIC Division</strong>
            </div>
            <div class="col-md-9">
                {{ request.divisi }}
            </div>
            <div class="col-md-3">
                <strong>Status</strong>
            </div>
            <div class="col-md-9">
                {% if request.statusrequest == 0 %}
                <span class="badge badge-warning">Draft</span>
                {% elif request.statusrequest == 1 %}
                <span class="badge badge-success">Submitted</span>
                {% else %}
                <span class="badge badge-danger">Cancel</span>
                {% endif %}
            </div>
            <div class="col-md-3">
                <strong>Preview Pdf</strong>
            </div>
            <div class="col-md-9">
                <button type="button" class="btn btn-dark btn-sm mt-1" id="btn-preview"><i class="fa-solid fa-magnifying-glass"></i> Preview</button>
            </div>
        </div>
    </div>
</div>

<hr />

<div class="card flex-fill">
    <div class="card-body">  
        <div class="question-part"></div>
    </div>
</div>

<hr />

<div class="card flex-fill">
    <div class="card-body">  
        <div class="workflow-part dx-container">
            <div id ="grid-main"></div>
        </div>
    </div>
    <div class="tablehtml" style="display: none;"> </div>
</div>

<hr />

<div class="card flex-fill">
    <div class="card-body">  
        <div class="row file-part"></div>
    </div>
</div>

<div class="button-area">
</div>

<div class="modal fade" id="preview-modal" tabindex="-1" role="dialog" aria-labelledby="preview-modal-Label"
    aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-xl">
        <div class="modal-content bg-light">
            <div class="form-group row">
                <style>
                    table {
                        width: 100%;
                        border-collapse: collapse;
                    }

                    td {
                        border: 1px solid rgb(0, 0, 0);
                        padding: 2px 5px;
                        white-space: pre
                    }

                    .ql-align-center {
                        text-align: center
                    }

                    .ql-align-justify {
                        text-align: justify
                    }

                    .ql-align-right {
                        text-align: right
                    }

                    p {
                        margin: 0;
                    }

                    td > p {
                        word-break: break-all;
                    }
                </style>
                <div id="testimoni" style="   
                padding:1cm;
                margin:1cm auto;
                border-radius: 5px;
                background: white;
                width: 21cm;
                height: 29.7cm;
                overflow: auto;">
                
                </div>
                <div class="form-group row col-12">
                    <div class="col text-center">
                        <button type="button" class="btn btn-secondary mb-3" data-bs-dismiss="modal">Close</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

{% block scriptcustom %}

<script src="{{ url_for('static', filename='js/page/submission/postingrequest.js') }}"></script>
<script src="{{ url_for('static', filename='js/page/submission/contentconverter.js') }}"></script>

{% endblock %}

app/templates/submission/request.html
{% extends 'layouts/main.html' %}

{% block content %}

<h3>{{ title }}</h3>

<div class="row mb-3">
    <div class="col-12">
        <div class="page-title-box d-flex align-items-center justify-content-between">
            <h4 style="color: transparent">Pepe Sedati</h4>
            <div class="page-title-right">
                <ol class="breadcrumb m-0" style="background-color: transparent">
                    <li class="breadcrumb-item"><a href="/home">Home</a></li>
                </ol>
            </div>

        </div>
    </div>
</div>

<div class="card flex-fill">
    <div class="card-header">
        <div class="card-actions float-end">
            <div class="dropdown position-relative"></div>
        </div>
    </div>
    <div class="card-body">
        <form class="row" action="{{ url_for('submissionbp.request_approval') }}" method="post">
            <input type="hidden" name="select-designdocument-version" id="select-designdocument-version">
            <input type="hidden" name="select-document-text" id="select-document-text">
            <div class="mb-3 col-md-6">
                <label class="form-label">Division Id</label>
                <select class="form-select flex-grow-1" name="select-division-id" id="select-division-id">
                </select>
            </div>

            <div class="mb-3 col-md-6">
                <label class="form-label">Document Type</label>
                <select class="form-select flex-grow-1" name="select-document-type" id="select-document-type">
                </select>
            </div>

            <div class="mb-3 col-md-12">
                <label class="form-label">Notes</label>
                <textarea class="form-control" name="textarea-notes" id="textarea-notes"></textarea>
            </div>

            <div class="col-md-12">
                <button class="btn btn-primary btn-next">Next</button>
            </div>
        </form>
    </div>
</div>

{% endblock %}

{% block scriptcustom %}

<script src="{{ url_for('static', filename='js/page/submission/request.js') }}"></script>

{% endblock %}

app/templates/submission/submissions.html
{% extends 'layouts/main.html' %}

{% block content %}

<h3>{{ title }}</h3>

<div class="row mb-3">
    <div class="col-12">
        <div class="page-title-box d-flex align-items-center justify-content-between">
            <h4 style="color: transparent">Pepe Sedati</h4>
            <div class="page-title-right">
                <ol class="breadcrumb m-0" style="background-color: transparent">
                    <li class="breadcrumb-item"><a href="/home">Home</a></li>
                </ol>
            </div>

        </div>
    </div>
</div>

<div class="card flex-fill">
    <div class="card-header">
        <div class="card-actions float-end">
            <div class="dropdown position-relative"></div>
        </div>
    </div>
    <div class="card-body">
        <form class="row">
            
            <div class="mb-3 col-md-6">
                <label class="form-label">Status request</label>
                <select class="form-select flex-grow-1" id="select-status-approval">
                    <option value="0">Draft</option>
                    <option value="1">Sent</option>
                </select>
            </div>

            <div class="col-md-12">
                <button type="button" class="btn btn-primary btn-filter">Filter</button>
            </div>
        </form>

        <div class="mt-5">
            <div id ="grid-main"></div>
        </div>
    </div>
</div>

{% endblock %}

{% block scriptcustom %}

<script src="{{ url_for('static', filename='js/page/submission/submissions.js') }}"></script>

{% endblock %}

app/templates/submission/uploadfilerequest.html
{% extends 'layouts/main.html' %}

{% block content %}

<h3>{{ title }}</h3>

<div class="row mb-3">
    <div class="col-12">
        <div class="page-title-box d-flex align-items-center justify-content-between">
            <h4 style="color: transparent">Pepe Sedati</h4>
            <div class="page-title-right">
                <ol class="breadcrumb m-0" style="background-color: transparent">
                    <li class="breadcrumb-item"><a href="/home">Home</a></li>
                    <li class="breadcrumb-item"><a href="/submission/submissions">Submission</a></li>
                    <li class="breadcrumb-item"><a href="/submission/submissions/fillformrequest/{{ request.requestapprovalid }}">Fill Form</a></li>
                    <li class="breadcrumb-item"><a href="/submission/submissions/authorizationrequest/{{ request.requestapprovalid }}">Auth Fill</a></li>
                </ol>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <input type="hidden" name="documentid" id="documentid" value="{{ request.masterdocid }}">
    <div class="col-md-3">
        <strong>Request Approval Id</strong>
    </div>
    <div class="col-md-9">
        <strong class="text-warning">{{ request.requestapprovalid }}</strong>
    </div>
    <div class="col-md-3">
        <strong>Request Approval Number</strong>
    </div>
    <div class="col-md-9">
        {{ request.requestapprovalnumber }}
    </div>
    <div class="col-md-3">
        <strong>Document Name</strong>
    </div>
    <div class="col-md-9">
        {{ request.name }}
    </div>
    <div class="col-md-3">
        <strong>Description</strong>
    </div>
    <div class="col-md-9">
        {{ request.desc }}
    </div>
    <div class="col-md-3">
        <strong>Status</strong>
    </div>
    <div class="col-md-9">
        {% if request.statusrequest == 0 %}
        <span class="badge badge-warning">Draft</span>
        {% elif request.statusrequest == 1 %}
        <span class="badge badge-success">Submitted</span>
        {% else %}
        <span class="badge badge-danger">Cancel</span>
        {% endif %}
    </div>
</div>

<hr />
<input type="hidden" name="requestapprovalid" id="requestapprovalid" value="{{ request.requestapprovalid }}" />
<div class="card flex-fill">
    <div class="card-header">
        <div class="card-actions float-end">
            <div class="dropdown position-relative"></div>
        </div>
    </div>
    <div class="card-body row">
        <label class="form-label mb-1">Do You Want to Upload An Attachment File?</label>
        <div class="form-check form-switch mb-3" style="padding-left: 3.5em;">
            <input class="form-check-input" type="checkbox" id="filequestion" name="filequestion" value="0">
            <label class="form-check-label" for="filequestion"><span id="yes-text">Yes</span> or <span id="no-text">No</span></label>
        </div>
        <div class="div-upload upload-area" style="display: none">
        </div>
        <div class="col-md-6">
            <div class="div-upload">
                <button type="button" class="btn btn-success col-12 btn-add"><i class="fa-solid fa-plus"></i>Add</button>
            </div>
        </div>
        <div class="col-md-6">
            <button type="button" class="btn btn-primary col-12 btn-next"><i class="fa fa-arrow-circle-right" aria-hidden="true"></i>Next</button>
        </div>
    </div>
</div>

{% endblock %}

{% block scriptcustom %}

<script src="{{ url_for('static', filename='js/page/submission/uploadfilerequest.js') }}"></script>

{% endblock %}