app/models/document.py
from app.models.base import BaseTable

class Document(BaseTable):

    def __init__(self):
        self.__database__ = 'mpmds'
        self.__tablename__ = 'masterdocument'
        self.__primarykey__ = "masterdocid"
        self.__fields__ = [
            "companyid",
            "divisionid",
            "departmentid",
            "name",
            "desc",
            "version",
            "status",
            "deleteflag",
            "createdby",
            "createddate",
            "modifby",
            "modifdate",
            "entryauth",
            "layout",
            "nosig",
        ]
        super().__init__()


    def list_document(self, companyid, divisionid, departmentid):
        result = []
        message = ""
        try:
            data, message = super().list_ordered()
            for x in data:
                show_data = False
                
                if companyid == "all" and divisionid == "all" and departmentid == "all":
                    show_data = True
                elif companyid == x[2] and divisionid == x[3] and departmentid == x[4]:
                    show_data = True
                
                if show_data and x[10] == 0: # delete flag
                    row = {
                        'masterdocid': x[0],
                        'documentnumber': x[1],
                        'companyid': x[2],
                        'divisionid': x[3],
                        'departmentid': x[4],
                        'isprint': x[5],
                        'name': x[6],
                        'desc': x[7],
                        'version': x[8],
                        'status': x[9],
                        'createddate': x[12],
                        'auth': x[15],
                        'layout': x[16],
                        'signature': x[17],
                        'activeversiondocument': x[18],
                    }
                    result.append(row)
        except Exception as e:
            print(str(e))
            result = None
            message = str(e)

        return (result, message)

    
    def list_document_for_request(self, npk, companyid, divisionid):
        result = []
        message = ""
        try:
            data, message = self.callproc("EXEC MPMDS_TIPEDOKUMEN_REQUESTAPPROVAL ?, ?", (npk, companyid,))
            for x in data:
                if x[10] == 0: # delete flag
                    row = {
                        'masterdocid': x[0],
                        'documentnumber': x[1],
                        'companyid': x[2],
                        'divisionid': x[3],
                        'departmentid': x[4],
                        'isprint': x[5],
                        'name': x[6],
                        'desc': x[7],
                        'version': x[8],
                        'status': x[9],
                        'createddate': x[12],
                        'auth': x[15],
                        'layout': x[16],
                        'signature': x[17],
                        'activeversiondocument': x[18],
                    }
                    result.append(row)
        except Exception as e:
            print(str(e))
            result = None
            message = str(e)

        return (result, message)


    def readone_document(self, key):
        result = None
        message = ""
        try:
            data, message = super().readone(key)
            if len(data) > 0:
                result = {
                    'masterdocid': data[0],
                    'documentnumber': data[1],
                    'companyid': data[2],
                    'divisionid': data[3],
                    'departmentid': data[4],
                    'isprint': data[5],
                    'name': data[6],
                    'desc': data[7],
                    'version': data[8],
                    'status': data[9],
                    'createddate': data[12],
                    'auth': data[15],
                    'layout': data[16],
                    'signature': data[17],
                    'activeversiondocument': data[18],
                }
        except Exception as e:
            print(str(e))
            result = None
            message = str(e)

        return (result, message)


    def update_activeversion(self, data):
        try:
            query = "UPDATE %s SET activeversiondocument=?, modifby=?, modifdate=? WHERE masterdocid=?" % (self.__tablename__)
            self.execute(query, (data["activeversiondocument"],data["modifby"], data["modifdate"], data["masterdocid"],))

            self.__connection__.commit()
            return(True, "success")
        except Exception as e:
            self.__connection__.rollback()
            print(str(e))
            return (False, str(e))


    def delete_document(self, masterdocid):
        try:
            query = f'''select a.* from requestapproval a where a.masterdocid=?'''
            data, message = self.execute(query, (masterdocid, ))

            if len(data) == 0:
                result, message = super().delete_flag(masterdocid)
                return(True, "success")
            else:
                return(False, "You can't delete Document that is already being used!")
        except Exception as e:
            self.__connection__.rollback()
            print(str(e))
            return (False, str(e))

app/forms/document.py
from flask_wtf import Form
from wtforms import StringField, TextAreaField, SelectField, BooleanField
import wtforms.validators as validators


class Document(Form):
    documentname = StringField('Document Name', validators=[
        validators.input_required(), validators.length(max=100)])
    documentdescription = TextAreaField('Document Description', validators=[
        validators.input_required(), validators.length(max=255)])
    documentversion = StringField('Document Version', validators=[
        validators.input_required(), validators.length(max=5)])
    documenttype = StringField('Document Type', validators=[
        validators.input_required()])
    documentstatus = SelectField('Document Status', choices=[('0', 'Inactive'), ('1', 'Active')], validators=[
        validators.input_required()])
    documentlayout = SelectField('Document Layout', choices=[('0', 'Portrait'), ('1', 'Landscape')], validators=[
        validators.input_required()])
    documentsignature = SelectField('Document Signature', choices=[('1', 'Yes'), ('0', 'No')], validators=[
        validators.input_required()])
    documentisprint = SelectField('Document Print?', choices=[('1', 'Yes'), ('0', 'No')], validators=[
        validators.input_required()])

    documentaccess_staff = BooleanField("Staff")
    documentaccess_supervisor = BooleanField("Supervisor")
    documentaccess_deputydepthead = BooleanField("Deputy Department Head")
    documentaccess_depthead = BooleanField("Department Head")
    documentaccess_deputydivhead = BooleanField("Deputy Division Head")
    documentaccess_divhead = BooleanField("Division Head")
    documentaccess_directur = BooleanField("Directur")

app/controllers/document.py
from flask import (
    Blueprint,
    render_template, 
    g,
    request,
    session,
    redirect,
    url_for,
    flash
)
import flask_login

from app import app
from app.forms import user as user_forms
from json import dumps

import datetime as dt
import json

# database
from app.models.user import User
from app.models.document import Document
from app.models.approval import Approval
from app.models.security import Security
from app.models.designdocument_groupquestion import DesignDocumentGroupQuestion
from app.models.designdocument_question import DesignDocumentQuestion
from app.models.designdocument_questioncondition import DesignDocumentQuestionCondition
from app.models.masterdocument_designdocument import MasterDocumentDesignDocument

# libraries
from app.libraries.session import usersession as USession

# forms
from app.forms import document as document_forms

# Create a document blueprint
documentbp = Blueprint('documentbp', __name__, url_prefix='/document')


@app.before_request
def before_request():
    g.user = None
    if 'user' in session:
        # find user based on userid, update information user
        user = session['user']
        g.user = user

        user = USession.User()
        # TODO: place your user / account data
        user.npk = g.user["npk"]
        user_data = User()
        person, message = user_data.profile(user.npk)

        if len(person) == 0:
            return render_template('handler/error.html', title='Error Page', message="Data user belum terdaftar di Approval Online")

        user.name = person['name']
        user.company = person['company']
        user.division = person['divisionid']
        user.department = person['departmentid']

        # save to session
        session["usersession"] = user.__dict__
        flask_login.login_user(user)


@documentbp.route('/api/1.0/documents')
@flask_login.login_required
def api_1_0_documents():
    # get company id 
    usersession = session["usersession"]
    companyid = usersession["company"]
    divisionid = usersession["division"]
    departmentid = usersession["department"]
    
    # try to get list of document
    document = Document()
    result, message = document.list_document(companyid, divisionid, departmentid)
    return {
        "success": "0" if result == None else "1",
        "message": message,
        "data": result
    }


@documentbp.route('/api/1.0/documentssubmissions/<divisionid>')
@flask_login.login_required
def api_1_0_documentssubmissions(divisionid):
    # get company id 
    usersession = session["usersession"]
    companyid = usersession["company"]
    departmentid = usersession["department"]
    
    # try to get list of document
    document = Document()
    result, message = document.list_document(companyid, divisionid, departmentid)
    return {
        "success": "0" if result == None else "1",
        "message": message,
        "data": result
    }


@documentbp.route('/api/1.0/document/delete', methods=['POST'])
@flask_login.login_required
def api_1_0_deletedocument():
    params = request.json

    document = Document()
    result, message = document.delete_document(params["documentid"])
    return {
        "success": "1" if result else "0",
        "message": message,
        "data": result
    }


@documentbp.route('/api/1.0/approvals/<documentid>')
@flask_login.login_required
def api_1_0_approvals(documentid):    
    approval = Approval()
    result, message = approval.list_approval(documentid)
    check_pemohon = "true" if any(x['pictype'] == 0 for x in result) else "false"
    return {
        "success": "0" if result == None else "1",
        "message": message,
        "data": result,
        "checkpemohon": check_pemohon
    }


@documentbp.route('/api/1.0/approval/parent/<documentid>')
@flask_login.login_required
def api_1_0_parentapproval(documentid):    
    approval = Approval()
    result, message = approval.list_approval_parent(documentid)
    return {
        "success": "0" if result == None else "1",
        "message": message,
        "data": result
    }


@documentbp.route("/api/1.0/approvals/insert", methods=["POST"])
@flask_login.login_required
def api_1_0_insertapproval():
    usersession = session["usersession"]
    approval = Approval()
    security = Security()
    params = request.json

    # check pic level, if = 0 -> do autogenerate
    piclevel = int(params["piclevel"])
    picsublevel = 1
    if piclevel == 0:
        piclevel, message = approval.get_maxlevel(params["documentid"])
        if piclevel == None:
            piclevel = 0
        piclevel = piclevel + 1
    else:
        picsublevel, message = approval.get_maxsublevel(params["documentid"], piclevel)
        picsublevel = picsublevel + 1

    # check if npk has email or not in mpmit_pic
    check, message = security.check_email_in_mpmit_pic(str(params["picid"]).zfill(5))

    if len(check) > 0:
        data = [
            {
                "masterdocid": params["documentid"],
                "pictype": int(params["pictype"]),
                "picid": str(params["picid"]).zfill(5),
                "piclevel": piclevel,
                "picsublevel": picsublevel,
                "mandatory": 1 if params["mandatory"] == "1" else 0,
                "descriptionapprovaltitle": params["description"],
                "createdby": usersession["npk"],
                "createddate": dt.datetime.now(),
                "modifby": "",
                "modifdate": "",
            }
        ]

        result, message = approval.insert(data)
    else:
        result, message = (False, f'''Data Email tidak ditemukan pada NPK {params["picid"]}!''')
    
    return {
        "success": "1" if result else "0",
        "message": message,
        "data": result
    }


@documentbp.route('/api/1.0/approvals/delete', methods=['POST'])
@flask_login.login_required
def api_1_0_deleteapproval():
    params = request.json

    approval = Approval()
    result, message = approval.delete(params["approveid"])
    return {
        "success": "1" if result else "0",
        "message": message if result else "<b>Authorization cannot be deleted because it has been</b> used <b>on Requested Approval!</b>",
        "data": result
    }


@documentbp.route('/browse')
@flask_login.login_required
def browse():
    if not g.user:
        return render_template('handler/error.html', title='Error Page', message="Harap lakukan login terlebih dahulu!")
    
    if g.user["npk"] != session["usersession"]["npk"]:
        return redirect('https://10.10.108.44/login')
    
    return render_template('document/browse.html', title='Documents')


@documentbp.route('/add', methods=['GET', 'POST'])
@flask_login.login_required
def add():
    if not g.user:
        return render_template('handler/error.html', title='Error Page', message="Harap lakukan login terlebih dahulu!")
    
    if g.user["npk"] != session["usersession"]["npk"]:
        return redirect('https://10.10.108.44/login')
    
    form = document_forms.Document(request.form)
    document = Document()

    if request.method=="POST":
        # check document is there or not with that name
        rowdoc, messagedoc = document.list_document("all", "all", "all")
        check = [x for x in rowdoc if x["name"].lower().strip().replace(" ", "") == form.documentname.data.lower().strip().replace(" ", "") and int(x["version"]) == int(form.documentversion.data)]

        if len(check) > 0:
            return render_template('document/add.html', title='Add - Documents', form=form, validation=True)

        # authorization
        authorization = ""
        if form.documentaccess_staff.data:
            authorization = authorization + "staff|"
        if form.documentaccess_supervisor.data:
            authorization = authorization + "supervisor|"
        if form.documentaccess_deputydepthead.data:
            authorization = authorization + "deputy department head|"
        if form.documentaccess_depthead.data:
            authorization = authorization + "department head|"
        if form.documentaccess_deputydivhead.data:
            authorization = authorization + "deputy division head|"
        if form.documentaccess_divhead.data:
            authorization = authorization + "division head|"
        if form.documentaccess_directur.data:
            authorization = authorization + "directur|"

        usersession = session["usersession"]
        data = [
            {
                "companyid": usersession["company"],
                "divisionid": usersession["division"],
                "departmentid": usersession["department"],
                "name": form.documentname.data,
                "isprint": form.documentisprint.data,
                "[desc]": form.documentdescription.data,
                "version": form.documentversion.data,
                "status": form.documentstatus.data,
                "deleteflag": 0,
                "createdby": usersession["npk"],
                "createddate": dt.datetime.now(),
                "layout": form.documentlayout.data,
                "nosig": form.documentsignature.data,
                "modifby": "",
                "modifdate": "",
                "entryauth": authorization
            }
        ]
        document = Document()
        result, message = document.insert(data)
        if result:
            return redirect(url_for('documentbp.browse'))    

    return render_template('document/add.html', title='Add - Documents', form=form, validation=False)


@documentbp.route('/edit/<documentid>', methods=['GET', 'POST'])
@flask_login.login_required
def edit(documentid):
    if not g.user:
        return render_template('handler/error.html', title='Error Page', message="Harap lakukan login terlebih dahulu!")
    
    if g.user["npk"] != session["usersession"]["npk"]:
        return redirect('https://10.10.108.44/login')
    
    form = document_forms.Document(request.form)
    document = Document()
    

app/templates/document/add.html
{% extends 'layouts/main.html' %}

{% block content %}

<h3>{{ title }}</h3>

<div class="card flex-fill">
    <div class="card-header">
        <div class="card-actions float-end">
            <div class="dropdown position-relative"></div>
        </div>
    </div>
    <div class="card-body">
        <form class="form" action="{{ url_for('documentbp.add') }}" method="post">
            {{ m.render_field(form.documentname, class='form-control') }}
            {{ m.render_field(form.documentdescription, class='form-control', rows=5) }}
            {{ m.render_field(form.documentversion, class='form-control', type='number') }}
            <div class="row">
                <div class="col-md-6">
                    {{ m.render_field(form.documentisprint, class='form-control') }}
                </div>
                <div class="col-md-6">
                    {{ m.render_field(form.documentlayout, class='form-control') }}
                </div>
                <div class="col-md-6">
                    {{ m.render_field(form.documentstatus, class='form-control') }}
                </div>
                <div class="col-md-6">
                    {{ m.render_field(form.documentsignature, class='form-control') }}
                </div>
            </div>

            <div class="mt-2">
                <h2>Access Authorization</h2>
                <div class="row mb-2">
                    <div class="col-6">{{ form.documentaccess_staff }} STAFF</div>
                    <div class="col-6">{{ form.documentaccess_supervisor }} SUPERVISOR</div>
                    <div class="col-6">{{ form.documentaccess_deputydepthead }} DEPUTY DEPARTMENT HEAD</div>
                    <div class="col-6">{{ form.documentaccess_depthead }} DEPARTMENT HEAD</div>
                    <div class="col-6">{{ form.documentaccess_deputydivhead }} DEPUTY DIVISION HEAD</div>
                    <div class="col-6">{{ form.documentaccess_divhead }} DIVISION HEAD</div>
                    <div class="col-6">{{ form.documentaccess_directur }} DIREKTUR</div>
                </div>
            </div>

            <!-- navigation save, cancel -->
            <div class="navigation-addedit">
                <div class="row">
                    <div class="col-md-6">
                        <a href="{{ url_for('documentbp.browse') }}" class="btn btn-light col-12" id="btn-cancel"><i class="fa fa-ban"
                                aria-hidden="true"></i>
                            cancel</a>
                    </div>
                    <div class="col-md-6">
                        {{ form.csrf_token }}
                        <button class="btn btn-primary col-12" id="btn-save" type="submit"><i class="fa fa-floppy-disk"
                                aria-hidden="true"></i>
                            save</button>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>

<script>
    var validation_insert = '{{ validation }}'
</script>

{% endblock %}

{% block scriptcustom %}

<script src="{{ url_for('static', filename='js/page/document/add.js') }}"></script>

{% endblock %}

app/templates/document/authorization.html
{% extends 'layouts/main.html' %}

{% block content %}

<h3>{{ title }}</h3>

<div class="row mb-3">
    <div class="col-12">
        <div class="page-title-box d-flex align-items-center justify-content-between">
            <h4 style="color: transparent">Pepe Sedati</h4>
            <div class="page-title-right">
                <ol class="breadcrumb m-0" style="background-color: transparent">
                    <li class="breadcrumb-item"><a href="/home">Home</a></li>
                    <li class="breadcrumb-item"><a href="/document/browse">Document</a></li>                   
                </ol>
            </div>
        </div>
    </div>
</div>

<div class="card flex-fill">
    <div class="card-header">
        <div class="card-actions float-end">
            <div class="dropdown position-relative"></div>
        </div>
    </div>
    <div class="card-body">
        <div class="row">
            <div class="col-md-3">
                <strong>Document Id</strong>
            </div>
            <div class="col-md-9">
                <input type="hidden" id="documentid-text" value="{{ document.masterdocid }}" />
                <strong class="text-warning">{{ document.masterdocid }}</strong>
            </div>
            <div class="col-md-3">
                <strong>Document Name</strong>
            </div>
            <div class="col-md-9">
                {{ document.name }}
            </div>
            <div class="col-md-3">
                <strong>Description</strong>
            </div>
            <div class="col-md-9">
                {{ document.desc }}
            </div>
            <div class="col-md-3">
                <strong>Status</strong>
            </div>
            <div class="col-md-9">
                {% if document.status == 1 %}
                <span class="badge badge-success">Active</span>
                {% else %}
                <span class="badge badge-danger">In-active</span>
                {% endif %}
            </div>
        </div>

        <hr />

        <div class="mt-5">
            <div id="grid-main"></div>
        </div>
    </div>
</div>

<!-- Modal -->
<div class="modal fade" id="authorization-modal" tabindex="-1" role="dialog" aria-labelledby="authorization-modal-Label"
    aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="authorization-modal-Label">Authorization</h5>
                <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form>
                    <div class="form-group">
                        <label for="authorization-pictype-select">Information</label>
                        <select class="form-control" id="authorization-pictype-select">
                            <option value="0">Pemohon</option>
                            <option value="1">Mengetahui</option>
                            <option value="2">Menyetujui</option>
                        </select>
                    </div>

                    <div id="master-pic-select">
                        <div class="form-group">
                            <label for="authorization-picapproval-select">Approval</label>
                            <select class="form-control" id="authorization-picapproval-select">
                                <option value="0">Free Text</option>
                                <option value="1">Master</option>
                            </select>
                        </div>

                        <div id="division-pic-select">

                            <div class="form-group">
                                <label for="authorization-picdivision-select">Division</label>
                                <select class="form-control" id="authorization-picdivision-select">
                                </select>
                            </div>

                            <div class="form-group">
                                <label for="authorization-picid-select">Approval Name</label>
                                <select class="form-control" id="authorization-picid-select">
                                </select>
                            </div>

                        </div>
                    </div>

                    <div id="free-text-select">
                        <div class="form-group">
                            <label for="authorization-name-text">Approval Name</label>
                            <strong>Pengisian oleh pembuat document</strong>
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="authorization-description-text">Approval Sign Title</label>
                        <input type="text" class="form-control" id="authorization-description-text" />
                    </div>

                    <hr />

                    <div class="form-group">
                        <input type="checkbox" id="authorization-mandatory-check" value="1" />
                        <label for="authorization-mandatory-check">Mandatory (Prohibited to skip)</label>
                    </div>

                    <div class="form-group">
                        <input type="checkbox" id="authorization-sublevel-check" value="1" />
                        <label for="authorization-sublevel-check">Save as sub-level at parent </label>
                        <select id="authorization-pic-parentlevel-select">
                            <option value="1">1. Pemohon - no name</option>
                        </select>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary btn-save"><i class="fa fa-floppy-disk"></i> Save</button>
            </div>
        </div>
    </div>
</div>

{% endblock %}

{% block scriptcustom %}

<script src="{{ url_for('static', filename='js/page/document/authorization.js') }}"></script>

{% endblock %}

app/templates/document/browse.html
{% extends 'layouts/main.html' %}

{% block content %}

<h3>{{ title }}</h3>

<div class="row mb-3">
    <div class="col-12">
        <div class="page-title-box d-flex align-items-center justify-content-between">
            <h4 style="color: transparent">Pepe Sedati</h4>
            <div class="page-title-right">
                <ol class="breadcrumb m-0" style="background-color: transparent">
                    <li class="breadcrumb-item"><a href="/home">Home</a></li>
                </ol>
            </div>

        </div>
    </div>
</div>

<div class="card flex-fill">
    <div class="card-header">
        <div class="card-actions float-end">
            <div class="dropdown position-relative"></div>
        </div>
    </div>
    <div class="card-body">
        <div id ="grid-main"></div>
    </div>
</div>

{% endblock %}

{% block scriptcustom %} 

<script src="{{ url_for('static', filename='js/page/document/browse.js') }}"></script>

{% endblock %}

app/templates/document/edit.html
{% extends 'layouts/main.html' %}

{% block content %}

<h3>{{ title }}</h3>

<div class="row mb-3">
    <div class="col-12">
        <div class="page-title-box d-flex align-items-center justify-content-between">
            <h4 style="color: transparent">Pepe Sedati</h4>
            <div class="page-title-right">
                <ol class="breadcrumb m-0" style="background-color: transparent">
                    <li class="breadcrumb-item"><a href="/home">Home</a></li>
                    <li class="breadcrumb-item"><a href="/document/browse">Document</a></li>
                    
                </ol>
            </div>

        </div>
    </div>
</div>

<div class="card flex-fill">
    <div class="card-header">
        <div class="card-actions float-end">
            <div class="dropdown position-relative"></div>
        </div>
    </div>
    <div class="card-body">
        <form class="form" action="{{ url_for('documentbp.edit', documentid=documentid) }}" method="post">
            {{ m.render_field(form.documentname, class='form-control') }}
            {{ m.render_field(form.documentdescription, class='form-control', rows=5) }}
            {{ m.render_field(form.documentversion, class='form-control', type='number') }}
            <div class="row">
                <div class="col-md-6">
                    {{ m.render_field(form.documentisprint, class='form-control') }}
                </div>
                <div class="col-md-6">
                    {{ m.render_field(form.documentlayout, class='form-control') }}
                </div>
                <div class="col-md-6">
                    {{ m.render_field(form.documentstatus, class='form-control') }}
                </div>
                <div class="col-md-6">
                    {{ m.render_field(form.documentsignature, class='form-control') }}
                </div>
            </div>

            <div class="mt-2">
                <h2>Access Authorization</h2>
                <div class="row mb-2">
                    <div class="col-6">{{ form.documentaccess_staff }} STAFF</div>
                    <div class="col-6">{{ form.documentaccess_supervisor }} SUPERVISOR</div>
                    <div class="col-6">{{ form.documentaccess_deputydepthead }} DEPUTY DEPARTMENT HEAD</div>
                    <div class="col-6">{{ form.documentaccess_depthead }} DEPARTMENT HEAD</div>
                    <div class="col-6">{{ form.documentaccess_deputydivhead }} DEPUTY DIVISION HEAD</div>
                    <div class="col-6">{{ form.documentaccess_divhead }} DIVISION HEAD</div>
                    <div class="col-6">{{ form.documentaccess_directur }} DIREKTUR</div>
                </div>
            </div>

            <!-- navigation save, cancel -->
            <div class="navigation-addedit">
                <div class="row">
                    <div class="col-md-6">
                        <a href="{{ url_for('documentbp.browse') }}" class="btn btn-light col-12" id="btn-cancel"><i class="fa fa-ban"
                                aria-hidden="true"></i>
                            cancel</a>
                    </div>
                    <div class="col-md-6">
                        {{ form.csrf_token }}
                        <button class="btn btn-primary col-12" id="btn-save" type="submit"><i class="fa fa-floppy-disk"
                                aria-hidden="true"></i>
                            save</button>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>

{% endblock %}

{% block scriptcustom %}

<script src="{{ url_for('static', filename='js/page/document/edit.js') }}"></script>

{% endblock %}