app/models/user.py
import xdrlib
from app.models.base import BaseQuery

class User(BaseQuery):

    def __init__(self):
        self.__database__ = 'mpmds'
        super().__init__()


    def profile(self, npk):
        result = []
        try:
            result, message = self.callproc("EXEC MPMIT_DATAUSER ?", (npk, ))
            person = {}
            for x in result:
                person = {
                    'npk': x[0],
                    'name':x[1],
                    'division':x[2],
                    'company':x[3],
                    'department':x[4],
                    'divisionid': x[5],
                    'departmentid': x[6],
                    'email':x[7],
                    'position':x[9],
                    'ttd': x[10],
                    'publickey':x[11]
                }
            return (person, message)
        except Exception as e:
            print(str(e))
            return (None, str(e))


    def insert_ttd(self, data, npk):
        try:
            query = "UPDATE mpmit.dbo.MPMIT_PIC SET ttd=?, modifby=?, modifdate=? WHERE npk=?"
            self.execute(query, (data["ttd"], data["modifby"], data["modifdate"], npk,))

            self.__connection__.commit()
            return(True, "success")
        except Exception as e:
            self.__connection__.rollback()
            print(str(e))
            return (False, str(e))

app/forms/user.py
from flask_wtf import Form
from wtforms import StringField, PasswordField
import wtforms.validators as validators


class SignUp(Form):
    first_name = StringField(
        'Name', validators=[validators.input_required(), validators.length(min=2)])
    last_name = StringField('Surname', validators=[
                            validators.input_required(), validators.length(min=2)])
    phone = StringField('Phone number', validators=[
                        validators.input_required(), validators.length(min=6)])
    email = StringField('Email address', validators=[
                        validators.input_required(), validators.email()])
    password = PasswordField('Password', validators=[
        validators.input_required(), validators.length(min=6), validators.equal_to('confirm', 'Passwords must match.')])
    confirm = PasswordField('Confirm password')


class SignIn(Form):
    userid = StringField('User Id', validators=[
        validators.input_required()])
    password = PasswordField('Password', validators=[
        validators.input_required(), validators.length(min=6)])

app/controllers/user.py
from flask import (
    Blueprint,
    render_template, 
    g,
    request,
    session,
    redirect,
    url_for,
    flash,
    send_file,
    send_from_directory,
    abort
)
import flask_login

from app import app
from app.forms import user as user_forms
import json
from json import dumps
import datetime as dt
import os
from xml.sax.saxutils import escape

from app.libraries.session import usersession as USession
from app.libraries.session import security as SecurityBase
from app.api import orange as Orange 

# database
from app.models.user import User
from app.models.security import Security

# Create a user blueprint
userbp = Blueprint('userbp', __name__, url_prefix='/user')


@app.before_request
def before_request():
    g.user = None
    if 'user' in session:
        # find user based on userid, update information user
        user = session['user']
        g.user = user

        user = USession.User()
        # TODO: place your user / account data
        user.npk = g.user["npk"]
        user_data = User()
        person, message = user_data.profile(user.npk)

        if len(person) == 0:
            return render_template('handler/error.html', title='Error Page', message="Data user belum terdaftar di Approval Online")

        user.name = person['name']
        user.company = person['company']
        user.division = person['divisionid']
        user.department = person['departmentid']

        # save to session
        session["usersession"] = user.__dict__
        flask_login.login_user(user)


@userbp.route('/signup', methods=['GET', 'POST'])
def signup():
    form = user_forms.SignUp(request.form)

    # form submit
    if request.method == 'POST' and form.validate():
        return redirect(url_for('index'))

    return render_template('user/signup.html', form=form, title='Sign Up')


@userbp.route('/signin', methods=['GET', 'POST'])
def signin():
    # if already login, redirect to home
    if 'usersession' in session and session["usersession"] is not None:
        return redirect(url_for('home'))

    form = user_forms.SignIn(request.form)

    # initialize sample input
    if request.method=="GET":
        form.userid.data = "05660"

    # form submit
    if request.method=="POST" and form.validate():
        apiOrange = Orange.OrangeAPI()
        password = escape(form.password.data)
        isValid = apiOrange.user_validation(form.userid.data, password)
        
        ## pass without API for development
        # process the login manager session
        user = USession.User()
        # TODO: place your user / account data
        user.npk = str(form.userid.data).zfill(5)
        user_data = User()
        person, message = user_data.profile(user.npk)

        if len(person) == 0:
            flash('Account is not found.', 'negative')
            return redirect(url_for('userbp.signin'))

        user.name = person['name']
        user.company = person['company']
        user.division = person['divisionid']
        user.department = person['departmentid']

        # save to session
        session["usersession"] = user.__dict__
        flask_login.login_user(user)
        if 'urlpage' in session and session['urlpage'] is not None:
            url = session['urlpage']["url"]
            return redirect(url_for(url, requestapprovalid=session['urlpage']["requestapprovalid"], period=session['urlpage']["period"]))
            # return redirect(f'''https://go.mpm-motor.com/approvalonline/monitoring/viewtracking/linksession/{session['urlpage']["requestapprovalid"]}/{session['urlpage']["period"]}''', code=302)
        else:
            return redirect(url_for('home'))

        # if isValid:
        #     # check login-key
        #     securitymodel = Security()
        #     base_sckey = securitymodel.createbase_secretkey(dt.datetime.now().strftime("%m/%d/%Y, %H:%M:%S"))
        #     result, message = securitymodel.check_loginkey(form.userid.data)

        #     # set private, public, & secret key
        #     private_key, public_key, secret_key = result['private_key'], result['public_key'], result['secret_key']

        #     # generate login-key
        #     securitybase = SecurityBase.SecurityKey()
        #     basekey = securitybase.generate_basekey()
        #     pk_key, pb_key = securitybase.generate_loginkey(basekey)

        #     # set data
        #     data = {
        #         "modifby": form.userid.data,
        #         "modifdate": dt.datetime.now()
        #     }

        #     # check if key from db none, then insert it to dict
        #     if private_key is None:
        #         private_key = pk_key
        #         data["private_key"] = private_key

        #     if public_key is None:
        #         public_key = pb_key
        #         data["public_key"] = public_key
                
        #     if secret_key is None:
        #         secret_key = securitybase.generate_secretkey(public_key, base_sckey)
        #         data["secret_key"] = secret_key

        #     # insert login-key to db
        #     if "private_key" in data or "public_key" in data or "secret_key" in data:
        #         result2, message2 = securitymodel.insert_loginkey(data, form.userid.data)

        #     # process the login manager session
        #     user = USession.User()
        #     # TODO: place your user / account data
        #     user.npk = form.userid.data
        #     user_data = User()
        #     person, message = user_data.profile(user.npk)
            
        #     if len(person) == 0:
        #         flash('Account is not found.', 'negative')
        #         return redirect(url_for('userbp.signin'))

        #     user.name = person['name']
        #     user.company = person['company']
        #     user.division = person['divisionid']
        #     user.department = person['departmentid']

        #     # save to session
        #     session["usersession"] = user.__dict__
        #     flask_login.login_user(user)
        #     if 'urlpage' in session and session['urlpage'] is not None:
        #         url = session['urlpage']["url"]
        #         # return redirect(url_for(url, requestapprovalid=session['urlpage']["requestapprovalid"], period=session['urlpage']["period"]))
        #         return redirect(f'''https://go.mpm-motor.com/approvalonline/monitoring/viewtracking/linksession/{session['urlpage']["requestapprovalid"]}/{session['urlpage']["period"]}''', code=302)
        #     else:
        #         return redirect(url_for('home'))
        # else:
        #     flash('Invalid account.', 'negative')
        #     return redirect(url_for('userbp.signin'))

    return render_template('user/signin.html', form=form, title='Sign In')


@userbp.route('/api/1.0/profile/upload', methods=['POST'])
@flask_login.login_required
def insert_ttd():
    user_data = User()
    params = request.json
    
    data = {
        "ttd": params['file'],
        # "modifby": session["usersession"]["npk"],
        "modifby": g.user["npk"],
        "modifdate": dt.datetime.now()
    }
    # result, message = user_data.insert_ttd(data, session["usersession"]["npk"])
    result, message = user_data.insert_ttd(data, g.user["npk"])

    return {
        "success": "1" if result else "0",
        "result": result,
        "message": message
    }


# @userbp.route('/signout')
# @flask_login.login_required
# def signout():
#     flask_login.logout_user()
#     session["usersession"] = None
#     flash('Succesfully signed out.', 'positive')
#     return redirect(url_for('index'))


@userbp.route('/signout')
def signout():
    if "user" in session:
        session.pop("user")
    g.user = None
    flash('Succesfully signed out.', 'positive')
    return redirect('https://10.10.108.44/login')


@userbp.route('/profile')
@flask_login.login_required
def profile():
    if not g.user:
        return render_template('handler/error.html', title='Error Page', message="Harap lakukan login terlebih dahulu!")
    
    if g.user["npk"] != session["usersession"]["npk"]:
        return redirect('https://10.10.108.44/login')
    # usersession = session["usersession"]
    usersession = g.user

    user = User()
    person, message = user.profile(usersession["npk"])

    # check login-key
    securitymodel = Security()
    securitybase = SecurityBase.SecurityKey()

    result, message = securitymodel.check_loginkey(usersession["npk"])
    
    base_sckey = securitymodel.createbase_secretkey(dt.datetime.now().strftime("%m/%d/%Y, %H:%M:%S"))

    # set private, public, & secret key
    private_key, public_key, secret_key = result['private_key'], result['public_key'], result['secret_key']

    # generate login-key
    securitybase = SecurityBase.SecurityKey()
    basekey = securitybase.generate_basekey()
    pk_key, pb_key = securitybase.generate_loginkey(basekey)

    # set data
    data = {
        "modifby": usersession["npk"],
        "modifdate": dt.datetime.now()
    }

    # check if key from db none, then insert it to dict
    if private_key is None:
        private_key = pk_key
        data["private_key"] = private_key

    if public_key is None:
        public_key = pb_key
        data["public_key"] = public_key
        
    if secret_key is None:
        secret_key = securitybase.generate_secretkey(public_key, base_sckey)
        data["secret_key"] = secret_key

    # insert login-key to db
    if "private_key" in data or "public_key" in data or "secret_key" in data:
        result2, message2 = securitymodel.insert_loginkey(data, usersession["npk"])

    hashed_seckey = securitybase.encrypt_md5_profile(secret_key)

    return render_template('user/profile.html', 
        title='Profile',
        person=person,
        key=hashed_seckey)


@userbp.route('/manual')
@flask_login.login_required
def manual():
    if not g.user:
        return render_template('handler/error.html', title='Error Page', message="Harap lakukan login terlebih dahulu!")
    

app/templates/user/browse.html
{% extends 'layouts/main.html' %}

{% block content %}

<main>
    <!-- browse user -->
    <section>
        <div class="container mt-2 mb-2">
            <h3>{{ title }}</h3>

            <div class="card flex-fill">
                <div class="card-header">
                    <div class="card-actions float-end">
                        <div class="dropdown position-relative"></div>
                    </div>
                </div>
                <div class="card-body">
                    <div id ="grid-main"></div>
                </div>
            </div>
        </div>
    </section>
</main>

{% endblock %}

{% block scriptcustom %} 

<script src="{{ url_for('static', filename='js/page/user/data.js') }}"></script>
<script src="{{ url_for('static', filename='js/page/user/browse.js') }}"></script>

{% endblock %}

app/templates/user/manual.html
{% extends 'layouts/main.html' %}

{% block content %}

<h3>{{ title }}</h3>

<div class="row">
    <div class="col-md-12">
        <div class="card mb-3">
            <hr class="my-0">
            <div class="card-body">
                <h5 class="h6 card-title">Manual Referensi Penggunaan</h5>
                <ul class="list-unstyled mb-0">
                    <li class="mb-1"><i class="fa fa-file"></i> Document <a href="{{ url_for('userbp.api_documentfile', params='UserManual-MasterDocument.pdf') }}">click here!</a></li>
                    <li class="mb-1"><i class="fa fa-cloud"></i> Submission <a href="{{ url_for('userbp.api_documentfile', params='UserManual-Submissions.pdf') }}">click here!</a></li>
                    <li class="mb-1"><i class="fa fa-desktop"></i> Report <a href="{{ url_for('userbp.api_documentfile', params='UserManual-ReportMonitoring.pdf') }}">click here!</a></li>
                </ul>
            </div>
            <hr class="my-0">
        </div>
    </div>
</div>

{% endblock %}

app/templates/user/profile.html
{% extends 'layouts/main.html' %}

{% block content %}

<h3>{{ title }}</h3>

<div class="row">
    <div class="col-md-4 col-xl-3">
        <div class="card mb-3">
            <div class="card-header">
                <h5 class="card-title mb-0">Profile Details</h5>
            </div>
            <div class="card-body text-center">
                <h5 class="card-title mb-0">{{ person.name }}</h5>
                <div class="text-muted mb-2">{{ person.position }}</div>

                <div>
                    <a class="btn btn-primary btn-sm" href="mailto:{{ person.email }}"><i class="fa fa-envelope"></i> Email</a>
                </div>
            </div>
            <hr class="my-0">
            <div class="card-body">
                <h5 class="h6 card-title">Working Information</h5>
                <ul class="list-unstyled mb-0">
                    <li class="mb-1">Division <a href="#">{{ person.division }}</a></li>
                    <li class="mb-1">Department <a href="#">{{ person.department }}</a></li>
                    <li class="mb-1"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"
                            fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"
                            stroke-linejoin="round" class="feather feather-briefcase feather-sm me-1">
                            <rect x="2" y="7" width="20" height="14" rx="2" ry="2"></rect>
                            <path d="M16 21V5a2 2 0 0 0-2-2h-4a2 2 0 0 0-2 2v16"></path>
                        </svg> Works at <a href="#">{{ person.company }}</a></li>
                </ul>
            </div>
            <hr class="my-0">
            <div class="card-body">
                <h5 class="h6 card-title">Digital Signature</h5>
                <div class="row text-center mt-2">
                    <div class="col-12">
                        <a href="#">
                            {% if person.ttd is not none %}   
                                <img src="{{ person.ttd }}" width="50%" id="img-sign" />
                            {% else %}
                                <img src="https://cdn-icons-png.flaticon.com/512/3456/3456420.png" width="50%" id="img-sign" />
                            {% endif %}
                        </a>
                    </div>
                    <div class="col-12">
                        <img src="https://apps.mpm-motor.com/it/mpmqrcode/Home?d={{key}}" width="50%" />
                    </div>
                    <div class="col-12">
                        <input type="hidden" id="userkey" value="{{ person.publickey }}">
                        <a href="#" id="usersession">{{ session["usersession"].id }}</a>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- <div class="col-md-8 col-xl-9">
        <div class="card">
            <div class="card-header">
                <div class="card-actions float-end">
                    <div class="dropdown position-relative">
                        <a href="#" data-bs-toggle="dropdown" data-bs-display="static">
                            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"
                                fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"
                                stroke-linejoin="round" class="feather feather-more-horizontal align-middle">
                                <circle cx="12" cy="12" r="1"></circle>
                                <circle cx="19" cy="12" r="1"></circle>
                                <circle cx="5" cy="12" r="1"></circle>
                            </svg>
                        </a>

                        <div class="dropdown-menu dropdown-menu-end">
                            <a class="dropdown-item" href="#">Action</a>
                            <a class="dropdown-item" href="#">Another action</a>
                            <a class="dropdown-item" href="#">Something else here</a>
                        </div>
                    </div>
                </div>
                <h5 class="card-title mb-0">Activities</h5>
            </div>
            <div class="card-body h-100">

                <div class="d-flex align-items-start">
                    <img src="img/avatars/avatar-5.jpg" width="36" height="36" class="rounded-circle me-2"
                        alt="Ashley Briggs">
                    <div class="flex-grow-1">
                        <small class="float-end">5m ago</small>
                        <strong>Ashley Briggs</strong> started following <strong>Stacie Hall</strong><br>
                        <small class="text-muted">Today 7:51 pm</small><br>

                    </div>
                </div>

                <hr>
                <div class="d-flex align-items-start">
                    <img src="img/avatars/avatar.jpg" width="36" height="36" class="rounded-circle me-2"
                        alt="Chris Wood">
                    <div class="flex-grow-1">
                        <small class="float-end">30m ago</small>
                        <strong>Chris Wood</strong> posted something on <strong>Stacie Hall</strong>'s timeline<br>
                        <small class="text-muted">Today 7:21 pm</small>

                        <div class="border text-sm text-muted p-2 mt-1">
                            Etiam rhoncus. Maecenas tempus, tellus eget condimentum rhoncus, sem quam semper libero, sit
                            amet adipiscing sem neque sed ipsum. Nam quam nunc, blandit vel, luctus
                            pulvinar, hendrerit id, lorem. Maecenas nec odio et ante tincidunt tempus. Donec vitae
                            sapien ut libero venenatis faucibus. Nullam quis ante.
                        </div>

                        <a href="#" class="btn btn-sm btn-danger mt-1"><svg xmlns="http://www.w3.org/2000/svg"
                                width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor"
                                stroke-width="2" stroke-linecap="round" stroke-linejoin="round"
                                class="feather feather-heart feather-sm">
                                <path
                                    d="M20.84 4.61a5.5 5.5 0 0 0-7.78 0L12 5.67l-1.06-1.06a5.5 5.5 0 0 0-7.78 7.78l1.06 1.06L12 21.23l7.78-7.78 1.06-1.06a5.5 5.5 0 0 0 0-7.78z">
                                </path>
                            </svg> Like</a>
                    </div>
                </div>

                <hr>
                <div class="d-flex align-items-start">
                    <img src="img/avatars/avatar-4.jpg" width="36" height="36" class="rounded-circle me-2"
                        alt="Stacie Hall">
                    <div class="flex-grow-1">
                        <small class="float-end">1h ago</small>
                        <strong>Stacie Hall</strong> posted a new blog<br>

                        <small class="text-muted">Today 6:35 pm</small>
                    </div>
                </div>

                <hr>
                <div class="d-flex align-items-start">
                    <img src="img/avatars/avatar-2.jpg" width="36" height="36" class="rounded-circle me-2"
                        alt="Carl Jenkins">
                    <div class="flex-grow-1">
                        <small class="float-end">3h ago</small>
                        <strong>Carl Jenkins</strong> posted two photos on <strong>Stacie Hall</strong>'s timeline<br>
                        <small class="text-muted">Today 5:12 pm</small>

                        <div class="row g-0 mt-1">
                            <div class="col-6 col-md-4 col-lg-4 col-xl-3">
                                <img src="img/photos/unsplash-1.jpg" class="img-fluid pe-2" alt="Unsplash">
                            </div>
                            <div class="col-6 col-md-4 col-lg-4 col-xl-3">
                                <img src="img/photos/unsplash-2.jpg" class="img-fluid pe-2" alt="Unsplash">
                            </div>
                        </div>

                        <a href="#" class="btn btn-sm btn-danger mt-1"><svg xmlns="http://www.w3.org/2000/svg"
                                width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor"
                                stroke-width="2" stroke-linecap="round" stroke-linejoin="round"
                                class="feather feather-heart feather-sm">
                                <path
                                    d="M20.84 4.61a5.5 5.5 0 0 0-7.78 0L12 5.67l-1.06-1.06a5.5 5.5 0 0 0-7.78 7.78l1.06 1.06L12 21.23l7.78-7.78 1.06-1.06a5.5 5.5 0 0 0 0-7.78z">
                                </path>
                            </svg> Like</a>
                    </div>
                </div>

                <hr>
                <div class="d-flex align-items-start">
                    <img src="img/avatars/avatar-2.jpg" width="36" height="36" class="rounded-circle me-2"
                        alt="Carl Jenkins">
                    <div class="flex-grow-1">
                        <small class="float-end">1d ago</small>
                        <strong>Carl Jenkins</strong> started following <strong>Stacie Hall</strong><br>
                        <small class="text-muted">Yesterday 3:12 pm</small>

                        <div class="d-flex align-items-start mt-1">
                            <a class="pe-3" href="#">
                                <img src="img/avatars/avatar-4.jpg" width="36" height="36" class="rounded-circle me-2"
                                    alt="Stacie Hall">
                            </a>
                            <div class="flex-grow-1">
                                <div class="border text-sm text-muted p-2 mt-1">
                                    Nam quam nunc, blandit vel, luctus pulvinar, hendrerit id, lorem. Maecenas nec odio
                                    et ante tincidunt tempus.
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <hr>
                <div class="d-flex align-items-start">
                    <img src="img/avatars/avatar-4.jpg" width="36" height="36" class="rounded-circle me-2"
                        alt="Stacie Hall">
                    <div class="flex-grow-1">
                        <small class="float-end">1d ago</small>
                        <strong>Stacie Hall</strong> posted a new blog<br>
                        <small class="text-muted">Yesterday 2:43 pm</small>
                    </div>
                </div>

                <hr>
                <div class="d-flex align-items-start">
                    <img src="img/avatars/avatar.jpg" width="36" height="36" class="rounded-circle me-2"
                        alt="Chris Wood">
                    <div class="flex-grow-1">
                        <small class="float-end">1d ago</small>
                        <strong>Chris Wood</strong> started following <strong>Stacie Hall</strong><br>
                        <small class="text-muted">Yesterdag 1:51 pm</small>
                    </div>
                </div>

                <hr>
                <div class="d-grid">
                    <a href="#" class="btn btn-primary">Load more</a>
                </div>
            </div>
        </div>
    </div> -->
</div>

{% endblock %}

{% block scriptcustom %}

<script src="{{ url_for('static', filename='js/page/user/profile.js') }}"></script>

{% endblock %}

app/templates/user/signin.html
{% extends "layouts/home.html" %}

{% block content %}

<div class="container mt-2 mb-2">

	<div class="form-signin">

		<div class="row card-signin py-4" style="margin: 0px 370px">
			<div class="card-signin-left col">
				<div class="card-signin-title mb-3">
					<h1>Sign In</h1>
				</div>

				<span class="text-warning mt-2 mb-2">You can use the orange's username</span>

				<form class="form" action="{{ url_for('userbp.signin') }}" method="post">
					{{ m.render_field(form.userid, class='form-control') }}
					{{ m.render_field(form.password, class='form-control') }}
					{{ form.csrf_token }}
					<button class="btn btn-large btn-block btn-primary form-control mt-3" type="submit">Sign In</button>
				</form>
			</div>

			<!--
			<div class="card-signin-right col">
				<div class="row">
					<h1 class="col-12"co>Hello, Friend!</h1>
					<h6 class="col-12">Enter your personal details and start journey with us</h6>
					<a href="{{ url_for('userbp.signup') }}" class="btn btn-large btn-block btn-dark mt-3">Sign Up</a>
				</div>
			</div>
			-->
		</div>

	</div>

</div>

{% endblock %}

app/templates/user/signup.html
{% extends "layouts/home.html" %}

{% block content %}

<div class="container mt-2 mb-2">

    <div class="form-signup">
        <div class="card-signup">
            <div class="card-signup-title">
                <h1>Create Account</h1>
                <span>Already have an account? <a href="/user/signin">Sign In</a></span>
            </div>

            <form class="form" action="/user/signup" method="post">
                {{ m.render_field(form.first_name, class='form-control') }}
                {{ m.render_field(form.last_name, class='form-control') }}
                {{ m.render_field(form.phone, class='form-control') }}
                {{ m.render_field(form.email, class='form-control') }}
                {{ m.render_field(form.password, class='form-control') }}
                {{ m.render_field(form.confirm, class='form-control') }}
                {{ form.csrf_token }}
                <button class="btn btn-large btn-block btn-primary form-control mt-3" type="submit">Sign Up</button>
            </form>

        </div>
    </div>

</div>

{% endblock %}